title: "Проект Солнце Москвы"
description: "Материалы исследования и ТЗ для редизайна moscow-sun.ru"
theme: just-the-docs

url: "https://igorkonovalchik.github.io"
baseurl: "/solnce-moskvy-docs"

aux_links:
  "REDLOFT.RU": "https://redloft.ru"
  "moscow-sun.ru": "https://moscow-sun.ru"

aux_links_new_tab: true

color_scheme: light

search_enabled: true

heading_anchors: true

back_to_top: true
back_to_top_text: "Наверх"

footer_content: "Подготовлено агентством <a href=\"https://redloft.ru\">REDLOFT.RU</a> · 2026"

plugins:
  - jekyll-seo-tag
